project:
  type: website

execute: 
  freeze: auto

website:
  title: "Harriet Mason"
  navbar:
    background: primary
    search: true
    left:
      - href: meetings/index.qmd
        text: Meeting Notes
      - href: ideas/index.qmd
        text: PhD Writings
      - text: Teaching
        menu:
          - text: ETC3250
            href: teaching/ETC3250.qmd
          - text: ETC3580
            href: teaching/ETC3580.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    from: markdown+emoji
 #   reference-location: margin
  #  citation-location: margin
