project:
  type: website

execute: 
  freeze: auto

bibliography: references.bib

website:
  title: "Harriet Mason"
  navbar:
    background: primary
    search: true
    left:
      - index.qmd
      - sidebar:teaching
      - href: meetings/index.qmd
        text: Meeting Notes
      - href: ideas/index.qmd
        text: Idea Write Ups
      
  sidebar:
    - id: teaching
      title: "Teaching"
      contents:
        - teaching/ETC3250.qmd
        - teaching/ETC3580.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    from: markdown+emoji
 #   reference-location: margin
  #  citation-location: margin
