---
title: "Meetings"
listing:
  - id: old-meetings
    contents: old-meetings/*.pdf
    type: table
    sort: "title desc"
---

# Supervisor Meetings
## 2023 March 23rd
#### CassowaryR
- I can't even install the newer version of the package. I have tried using a couple methods and none of them worked.
- Should I email back and say I can't install the package?

#### General
- I think I want to change the direction of my topic a little bit, interesting in everyone's thoughts.



## 2023 March 16th
#### General
- I added Sarah as a supervisor
- My github actions broke for a bit so my meeting notes weren't updating.

#### Milestone
- I got the reminder email that my milestone is due in 2 months
- I am still not entirely sure what I have to do for it

#### Uncertainty Literature Review
- Have enough reading to start filling out the uncertainty breakdown blog post, found [here](https://harriet.quarto.pub/posts/what_is_uncertainty/).
- Currently adding stuff as we speak

#### CassowaryR
- I have read Alberts email but I haven't checked the new version of interp. I will do that before emailing him back, hopefully before next week.
- He suggested adding random noise, for the long computation issue. The delauney triangulation SHOULD work with colinear points and considering the striated scagnostic literally counts the number of points in a straight line, I am not the biggest fan of that solution. Cassowaryr also already includes jitter for perfectly colinear points (i.e. the straight lines) and while the code runs without error I feel like it opens up some new issues. It means the MST and the hulls the scagnostic are calculated on are not the ones the user sees, and we have already seen that small changes to the triangulation can throw those quite off balance. Plus it now makes it invisible to cassowaryr if points are in a perfectly straight line, and I don't wan't that to be invisible.
- Additionally, if we intend to use cassowaryr for projection persuit where we aren't unitizing the projection every time we calculate the scagnostics, a set amount of random noise will have more effect on some projections than others. 
- He also didn't mention the readability of the C package, nor the scatter plot that had an error, but I will double check those too.
- He showed the different plots for a larger N, which we already knew interp was faster. This might be why he is not keep on swapping packages (excluding the extra work). I wonder if he would be willing to include tRiad as an option (although he might not go for it because it increases his dependencies).

#### Meetings comments and notes
- Additional issue with adding noise in the interp function. Once we add binning to the package and start implementing it, we dont want to be adding noise afterwards. It's a bit weird.
- Can try writing an intermediate function to take the tRiad output and make it look like the interp::tri.mesh() output so tRiad can be seamlessly integrated. 
- Some terms in the uncertainty are a bit odd. Maybe I should write a glossary.
- The forecast display does not make it clear the uncertainty in the model if determined by the residuals of the fitted values. Interesting to see if displaying the fitted values on the forecast makes people see more vs less uncertainty. 


## 2023 March 9th

#### General
* Set up github actions so the meeting notes are always up to date.

#### Uncertainty Literature Review
- Just read papers this week, didn't write anything new.

#### CassowaryR
- I fixed the github actions issue, the github actions themselves needed to be updated, it was nothing wrong with the dependencies or code.
- I wrote out a motivation that could be sent to the author of alphahull as to why the swap from interp to tRiad is necessary. It can be found [here](triad/triadswap.qmd)

## 2023 March 2nd
  
#### General
- I made this website to store information and posts and stuff. It keeps everything together which I like.
  
#### Uncertainty Literature Review
- Finished writing the first blog post and published on this website under [posts](https://harriet.quarto.pub/posts/)
  
#### Experiemnts
- Made a list of [experiment ideas](https://harriet.quarto.pub/research/ideas.html) from the "why people don't visualise uncertainty" topic which is on the website. 
- Added some other experiment ideas for future sections (although I haven't read that much literature on the topics so I am not sure if they are good ideas or not)
  
#### CassowaryR
- Made the hex sticker and added it to the [repo](https://github.com/numbats/cassowaryr) (finally)
- The build and stuff work locally on my computer, but fail in the github actions. They all have the same error and I don't know what it means.
  
#### Meetings comments and notes
- To test if people are more likely to visualise uncertainty if it is set as a default, make two packages for people to visualise uncertainty. One where the default is uncertainty and one where it isn't and see if people just leave the default or if they don't like the uncertainty so much they change it. Would need to do some finessing so it is not obvious it is Robs package.
- To test if including uncertainty is the best way to show the differentiation between the data and the forecast compare uncertainty to other methods of differentiating the forecast. Other methods such as a gap, a change in the line colour, or a change in background colour.
- People are often presented with risk as odds relative to the average (e.g. your area has 3x more cancer cases than the average). Could be good to test this method of conveying odds relative to a population level (60 people in your area of 10 000 have cancer and the average is 20 per 10 000).
- To test the cognative overload of uncertainty, we can show different designs and see how long it takes to answer a question on it. Alternatively we can fix the time and see which plot gives people the most accuracy. Try to find a motivating example. If we want to compare it to not visualising at all and just displaying threshold values, create a ladder of choices or categories, however in general it is hard to quantify continuous uncertainty.
- Energy data may be a good motivating example for the fan vs paths display of forecasting uncertainty. Di emailled it as an RDS.

## 2022-2023 February 9th
::: {#old-meetings}
:::