---
title: "Meetings"
listing:
  - id: old-meetings
    contents: old-meetings/*.pdf
    type: table
    sort: "title desc"
---

# Supervisor Meetings
## 2023 August 
#### IEEEVIS Poster
- The deadlines have been changed a little
  - The abstract is due August 15
  - A PDF of the poster is due August 31
  - The video still says it is due September 22 but it also says "needs to be submitted with the 2-page abstract" so I'm not sure what they want with that one.

## 2023 July 27
#### BEX6510
- Unit started this week so I will not be able to do as much research every week

#### AEMO meeting
- I think it went well
- Told to check out early 2017 load shedding in two states as a case study as well.
- Areil also suggested looking at something to do with forecasting in wind turbines, he said he mentioned it to Sarah a couple of months ago and she would know what he was talking about.

#### IEEEVIS Poster
- I understand the feedback but and not entirely sure how to action some of it 
  - I don't know how to add in extra uncertainty sources when the limit is so small (and I am not sure if I have read the uncertainty sources they are talking about)
  -  I couldn't figure out the formatting of the abstract before and I could not work out what I was doing wrong.
  
#### Notes
- important to point to taxonomies and note that expanded on literature review documenting existing work 
- If you cite one paper and the reader can go to that paper and find others you can get away with only citing that papers (like review papers)
- start with eye catching element (visible from a distance as a starting point), make it obvious the direction they are supposed to read the poster in
- think about what kind of discussions you want to have with people, what do you want people to ask you about or comment on and focus poster to hint in that direction. people can come up ask the weirdest things.

## 2023 July 20
#### VYT
- I didn't get time to finish the video but I did submit it haha
- I can show you the version I submitted
- I want to finish it later so that I have a video I want to send to people, but it is not a priority at the moment

#### AEMO meeting
- My phone needed to be replaced (it short circuited on Sunday) and a friend from Queensland was visiting yesterday/today so I haven't had a chance to do this yet.
- Should I show the VYT submission? Could be a useful opportunity to use it haha.

#### Notes
- Show AEMO related plots (could sketch something)
- Check with Bonsoo (email) need lectures recorded, and preferably some readable version of the slides or a textbook or something.

## 2023 July 13
#### This week I have...
- Literally only worked on my VYT submission but I think it's really good
  - I only have a little bit of the animation left, then I just need to do the outlines and shading and I'm done.
  - I want to show you what I have so far and get some feedback
 
#### Notes
- multivariate before spatial-temporal
- energy, weather, time, space variables
- also convey gross vs nice teletubby with colour
- make frankenstein teletubby cute

## 2023 July 6
#### This week I have...
- Am halfway through my VYT submission that is due Monday
- Had the academic writing meeting and we both agreed that with a proof read for "formality" I can change my writing to be more formal if I need to
- Daily tasks: a brief read of 2 papers from the paper pile and summarising an experimental paper for the taxonomy (These will basically always be daily but I keep them here because they do take up an hour or 2 every day and don't produce anything for you guys to look at)


## 2023 June 29
#### This week I have...
- Submitted IEEE VIS paper
- Booked an academic writing session with a learning advisers for next Tuesday.
- Had AEMO meeting with control room operator
- Started compiling the method information from experimental papers (not available on site yet because I need to clean it up)
- Started VYT draft

#### Academic writing
- I read the library resources on academic writing and realised I do in-fact know how to do it, I just don't like writing that way. 
- Objective and passive voice are easy to implement, but a formal voice is a little more difficult to implement. I think I strugggle to tell the difference between formal writing and boring (dry) writing.
- Regardless, I did book the meeting with the academic writing person at the library to make sure I can fix it if I need to. 

#### AEMO
- I think it would be helpful if they had an operations guide or something.
- A debreif would be good. I was a little lost tbh.

#### Notes
- R pacakge weatheroz (didn't work very well)
- have to pull solar radiation infor from noaar package
- Sherry expert in pulling weather data, try talking to her

## 2023 June 22
#### Todo Things
- IEEE Vis
  - I haven't done the poster submission yet. I'm going to
- Confirmation Feedback Adjustments
  - I think a problem with my confirmation report is that I was responding to a bunch of papers that nobody has read. Organising the papers that compare plots into some kind of data set might help provide context for what I'm saying.
  - I have done a lot of examples of particular aspects of my idea but one example that captures the whole idea would probably be better
  - Map presentation questions back to each paper
  - I think these things would also help me iron out the idea work on it after I finish marking.
- AEMO meeting on Wednesday (hash out potential examples to help refine)
- VYT
- Check cassowaryr paper works with interp

#### Notes
- Confirmation questions
  - if you have the taxonomy, do you have an example of where it would help if you didn't have it
    - From what you have read so far an example where having that taxonomy would help you organise that material
  - is this a way to make better visualisations or improve/assess visualisations that already exist
  - Jess said use example from AEMO
  - not clear what problem I'm solving
  - lit review might be too broad and too hard to do
  - Less focus on Jessica Hullman's work
  - AEMO Example - what do they consider uncertainty, maybe not 5 estimated outcomes
  - Clean up rational of each question of presentation (innovative format to tackle) refine it
  - write down why we had each question (directly from papers) map back to each paper
  - run a wider study and doing it as a study (maybe funding from scholarship/prolifico - crowd sourced user study)
  - Talk to someone about confirmation report and what it means for writing to be more scientific (talk to person in library or IT faculty or ChatGPT (haha))

## 2023 June 1
#### Confirmation
- Wildly different from when I started. I expected as much which is why I didn't start for so long haha.

#### Presentation
- I added the presentation to the confirmation section
- Can I structure my confirmation as a game show? I think it would make it interesting and engaging for the audience. I did it once in 8th grade for a report and setting up the information as a precursor for quiz questions tried to ensure people

#### VYT
- I registered for the visualise your thesis competition. Deadline is mid-July. It will give me something fun to work on off the back of the the confirmation. I used to make educational stop motion youtube videos when I was a teenager haha.

## 2023 June 1

#### Confirmation Report
- Working on the draft right now, you can see my progress [here](https://harriet.quarto.pub/harriet-mason/ideas/#confirmation-report)
- I'll message the slack when its readable and the edits I am making are smaller, hopefully by Wednesday afternoon.

##### Report Questions
- I feel like I should include a HOPS plot but I'm not sure how since it's an animation. I could use a screenshot of the visualisation in the paper but I don't know how to replicate it in R.
- multiple labeled frames to highlight animation under figure 1
- Express marginal and conditional distributions using formal math $f(PPM|Solution=A)$ and $f(PPM|Solution=B)$

### NOTES
- Boostrapping = resampling w replacement - keep side same (calls it permutaiton typically take two groups and scramble lables (sampling from propulation with no difference not changing dist))
- Chapter 1 add: Need to prodive evidence this abstraction is better. Link to concrete analytical work - link back to a particular framework - study to show why that particular one.
- doesn't need empirical evidence but does need to be really well motivated why you want to go in that direction
- In process of applying for ethics and hopefully after confirmation (one for AEMO and one for experiment)  - discussion with them might be recorded - once recording info if want to put quote in thesis need ethics approval - Need better understanding of the problem we are focusing on
- expand on chapter three - make suggestions on what *could* be there - e.g. software for visualising uncertainty specifically for energy output - how this applies for different types of plots and package makes it easy to make those plots. - not just technical but other application areas (translation) - applications of the framework in the energy sector, doesnt just need to be technical outputs can be the work being used in energy and generalised. Show it is beneficial and useful.
- no justification for why an R package and why do it (integrated into data analysis workflow)
- need to make it clearer that scholarship is from AEMO. investement from them and a case study. 
- mention talking to aemo people (title of their group and names of people) - show in conversations - also publication they sent
- cassowaryr - link to energy data with masses of different time series - characterise of feature sets - variation and uncertainty - shows done more work (mention in topic 3 looking at technical outputs can be used for energy been working on package) - looking to see how they match and overlap (different time series from lots of sources and scales pending further investigation) (add to chapter 3 details how this would work and how it relates to energy data)
- connect to academics with questions at the begining (academics love a table of results with confidence intervals make it relatable to people on the comitee)
- above all else show the data - Edward tufte 
- enough information to answer a question relates to concept of sufficiency
- maybe make distributions not asusmed more clear
- change colour scheme
- Being sure is good; being uncertain is not necessarily bad. https://www.nature.com/articles/nmeth.2530

## 2023 May 25
This has been a week of trying to fix endless technical issues :(

#### General
- I want to have the supervisor meeting every fortnight. Having it every week is stressful and I always feel like I haven't had enough time to properly work on what you guys told me to do in the last meeting before you present new stuff for me to do. This leaves me with 50 unfinished pieces of work and I just want more time to finish things.

#### Cassowaryr
- Writing up new issues and haven't been able to solve the tRiad problem. It might be because I messed around with stuff to get tensorflow working but idk. Current state is [here](triad/interpcheck.qmd)

#### Confirmation Report
- I started an outline and after a lot of struggling got it to output as a PDF [here](https://harriet.quarto.pub/harriet-mason/ideas/#confirmation-report)
- Should I make the confirmation report its own repo?
- Is there an existing template I should use?
- When do you guys want a draft of the report by?

#### Visualising uncertainty
- I have been organising the literature I've read on plots and most of it is just drawings in my notes app (so not on the blog). Thinking of working forwards from what Emi suggested last week so I have an idea of the overarching groups of plots and their related questions (using current research) 

### Notes
- https://ieeevis.org/year/2023/info/call-participation/posters (Poster submission after comfirmation report) - in Melbourne 
- Think about research outcomes of each section (and its research contributions) some technical and some theoretical and some use
- Reread original research motivation
- Draft of report by next week
- Confirmation report fine where it is but eventually need thesis repo
- Look at book Sarah suggested on how/why

## 2023 May 18
#### AEMO Meetings
- I emailed Dean and CCed all of you. He said he would set up a meeting.

#### Visualising uncertainty
- Part 3 [here](https://harriet.quarto.pub/ideas/parts/uncertaintyisdecisions/). It is very messy and unreadable and I'm currently trying to organise my ideas.


## 2023 May 11
#### AEMO Meetings
- Map of plan and draft email for AEMO people [here](aemo/aemoplan.qmd)
- Was I supposed to discuss this with Dean or was I supposed to make this and bring it to him?
 
#### cassowaryr
- I tried to install from CRAN and I ran into the same problem. 
- I genuinely have no idea what he is talking about with method 2. Have you guys done anything like that before? I read the stuff he provided and don't even know where to start.

### Notes
- task taxonomies

## 2023 May 4
#### Confirmation
- Should we try and organsise a top three dates? (If everyone is here). It looks like we won't be able to get a date with everyone that Catherine can chair.
- Skim read confirmation reports Di sent me. @Sarah if you have some you think would be helpful for me to read, I would also be keen to read those.
- It looks like the format goes: motivation/literature reivew, brief mentions of scope of 3 the three projects, detailled explanation of project 1 work to date, general discussion of plans for the other two projects, broad timeline of the phd.
- Since I have done an amount of cassowaryr work in the first year, should I detail that in the confirmation report even though its the third topic?
- Should I write it in the abbreviated report format? Is there a template for either of these I should use?

#### Visualising uncertainty
- Should I organise another meeting with Dean?
- Started applying taxonomy to example [here](https://harriet.quarto.pub/ideas/what_is_uncertainty/#applying-the-typology).

### Notes
#### WA AEMO meeting
- What do we want from them relative to my work
- How often should we meet
- What data are we working with
- Worthwile to map out what types of things we want to do with them before just jumping in
- Worthwhile to think of exploratory stage (if you have problems early on in your modelling and data processing - weather patterns which are pretty consistent) to be able to diagnose models (where do you not have sufficient information)
- Interested in workflow
- Split issues and EDA and communication perspective and map out what data would be related to each one. (could get sample or aggregate - want to keep geographical information in tact or disclosure agreement). 
- Could get access ourselves rather than waiting for them to give us access
- Look at AEMO data - seen this on your website, do you have a finer detail of data we could use.

#### Cassowaryr and Thesis
- How does cassowaryr link to entire thesis, is it related or is it a side research project that develops research skills
- Include if it can be linked to overarching ideas

## 2023 April 27
#### General
- Teaching ends up taking up a lot of time, especially in later weeks. I don't think I'll teach next semester.
- Github actions arent working and Github token has expired so meeting notes haven't been updating. Will fix before next week.
  
#### ASC
- Wrote poster abstract submission

#### Visualising uncertainty
- Had a meeting with Dean Sharafi, Toby Price and Alireza Fereidouni about the problems with uncertainty that AEMO is facing in WA. The meeting was recorded if you guys want to watch it. They asked if I wanted to work with them on their issue. Said I would go back to you guys and see what you think.
- I ironed out the definition/typology of uncertainty a little more [here](https://harriet.quarto.pub/ideas/what_is_uncertainty)

## 2023 April 20
#### Visualising uncertainty
- Started writing a mathematical definition of uncertainty in part 2 [here](https://harriet.quarto.pub/ideas/what_is_uncertainty/#defining-uncertainty). I am not sure how deep the mathematical definition should go. I was working through it with Tom and 

#### Cassowaryr
- Tried and failed to install interp usig gitlab. Emailled Albercht again. Haven't tried the new installing method that he emailled back


## 2023 April 6
#### General
- I have split the website in two. This website contains meetings notes, teaching help sheets, and written out research ideas. I have also changed the layout and structure.
- I moved blog posts and other public stuff to [netlify](https://harrietmason.netlify.app/). This fixes the size issue for the website and also draws a line between the blog posts and the research posts.

#### Last weeks meeting
- I have spoken to Di already and Ursula isn't here this week so it might not be beneficial to talk about it.
- If there is something you don't understand (or don't understand the whole thing) when I am presenting something I want you guys to tell me or ask about it. Otherwise I don't know what part is the problem and I don't know if the idea is bad or you just don't understand it. I got upset last week because the suggestions and the direction you guys thought I wanted to go with the research made it clear I didn't properly convey what I wanted to do, but the suggestions implied the idea was bad instead of implying a misunderstanding. That's why I was also upset when you suggested the work was good, since it was still clear I hadn't conveyed the idea and it wasn't persuasive.
- If I am going to the effort to explicity ask for something or make it clear its not possible, it is not really negotiable. There are a lot of research topics, so if I am aginst one thing that doesn't mean I am against everything. I am happy to make concessions in other areas, but often it takes a lot of effort for me to tell you guys that something is off the table so I need to it to be understood when I do. Otherwise I will just end up ignoring your advice because I already made it clear what I am and am not willing to do.
- I know there are four of you so you cant all stay updated on meeting notes, so I have tried to make the website more digestible so you can just read it to catch up.
- Also, since I start with an overview and work my way down, citations are the last thing I usually add to my writing. That means when I present a topic I will essentially never have citations. That does not mean I am not basing my work off evidence, it means I haven't done the citations yet.
- Please tell me if there is anything I can do to better communicate with you guys. I am happy to make changes to how I do things, but I don't know if nobody tells me anything.

#### Visualising uncertainty
- Rather than give piece by piece what I am trying to do, I have written up a motivation and outline of my idea [here](https://harriet.quarto.pub/ideas/) and will fill the sections with more detail as I go. Hopefully this will give you guys a better understanding of what I am trying to convey and why I don't want to work on spatial or temporal uncertainty specifically. In the overview I ended up just re-explaining the entire idea because I don't know which parts you guys are confused on so it might seem a little repetitive, sorry. I also included parts that I haven't written yet in the outline to give a better idea of where I want to go with the idea. If you don't understand parts please ask and I will focus on trying to explain that part better. If you fully get the idea and have criticism of it I'm open to hearing it. There are no citations, not because I don't have evidence to back up my claims, but because I typically do citations last. I can describe a paper that backs up each of my points from memory and send it to you if you want, so please don't say I have nothing to back up my claims when I present an overview like this.
- I have removed the intro bits from the posts. I was including them because starting with a diary entry helped me write about the research, but I think they make the posts longer and more difficult to read. I'm going to keep them in the public blog posts, but the private ones will just have the research information.

#### Notes
- write abstract for Australian Statistical Conference poster and show next week
 
## 2023 March 29
#### General
- The blog site is too big for quarto.pub which is why I had issues publishing my stuff this week :(. 
- I'm not sure if I should move the whole thing somewhere else, or just move the blog.

#### CassowaryR
- I haven't tried the GitLab link from Albrecht yet. I will do that soon.

#### Uncertainty Visualisation
- I did a manic word vomit about visualising uncertainty and my issues with it, its in the blog posts section but you can just use this [link](https://harriet.quarto.pub/posts/uncertaintyisdecisions/).
- I think I am leaning towards making a guide or something on how to visualise uncertainty based on the decision you want to make, not based on the type of data? Similar to the rules we have for normal visualisation? IDK.

#### Comments
- I need to establish ground rules for the next meetings.
- I don't want to do work that will turn out to be obsolete with other work. You keep asking me to zoom in but what if what I wan't to do as my first topic is establish rules for uncertainty visualisation the way we have rules for other visualisation.

## 2023 March 23
#### CassowaryR
- I can't even install the newer version of the package. I have tried using a couple methods and none of them worked.
- Should I email back and say I can't install the package?

#### General
- I think I want to change the direction of my topic a little bit, interesting in everyone's thoughts.

#### Comments
- Sarah is contacting people that I can talk to from AEMO and I should contact Sayani so that I can better understand what their problems are.

## 2023 March 16
#### General
- I added Sarah as a supervisor
- My github actions broke for a bit so my meeting notes weren't updating.

#### Milestone
- I got the reminder email that my milestone is due in 2 months
- I am still not entirely sure what I have to do for it

#### Uncertainty Literature Review
- Have enough reading to start filling out the uncertainty breakdown blog post, found [here](https://harriet.quarto.pub/posts/what_is_uncertainty/).
- Currently adding stuff as we speak

#### CassowaryR
- I have read Alberts email but I haven't checked the new version of interp. I will do that before emailing him back, hopefully before next week.
- He suggested adding random noise, for the long computation issue. The delauney triangulation SHOULD work with colinear points and considering the striated scagnostic literally counts the number of points in a straight line, I am not the biggest fan of that solution. Cassowaryr also already includes jitter for perfectly colinear points (i.e. the straight lines) and while the code runs without error I feel like it opens up some new issues. It means the MST and the hulls the scagnostic are calculated on are not the ones the user sees, and we have already seen that small changes to the triangulation can throw those quite off balance. Plus it now makes it invisible to cassowaryr if points are in a perfectly straight line, and I don't wan't that to be invisible.
- Additionally, if we intend to use cassowaryr for projection persuit where we aren't unitizing the projection every time we calculate the scagnostics, a set amount of random noise will have more effect on some projections than others. 
- He also didn't mention the readability of the C package, nor the scatter plot that had an error, but I will double check those too.
- He showed the different plots for a larger N, which we already knew interp was faster. This might be why he is not keep on swapping packages (excluding the extra work). I wonder if he would be willing to include tRiad as an option (although he might not go for it because it increases his dependencies).

#### Meetings comments and notes
- Additional issue with adding noise in the interp function. Once we add binning to the package and start implementing it, we dont want to be adding noise afterwards. It's a bit weird.
- Can try writing an intermediate function to take the tRiad output and make it look like the interp::tri.mesh() output so tRiad can be seamlessly integrated. 
- Some terms in the uncertainty are a bit odd. Maybe I should write a glossary.
- The forecast display does not make it clear the uncertainty in the model if determined by the residuals of the fitted values. Interesting to see if displaying the fitted values on the forecast makes people see more vs less uncertainty. 


## 2023 March 9

#### General
* Set up github actions so the meeting notes are always up to date.

#### Uncertainty Literature Review
- Just read papers this week, didn't write anything new.

#### CassowaryR
- I fixed the github actions issue, the github actions themselves needed to be updated, it was nothing wrong with the dependencies or code.
- I wrote out a motivation that could be sent to the author of alphahull as to why the swap from interp to tRiad is necessary. It can be found [here](triad/triadswap.qmd)

## 2023 March 2
  
#### General
- I made this website to store information and posts and stuff. It keeps everything together which I like.
  
#### Uncertainty Literature Review
- Finished writing the first blog post and published on this website under [posts](https://harriet.quarto.pub/posts/)
  
#### Experiemnts
- Made a list of [experiment ideas](https://harriet.quarto.pub/research/ideas.html) from the "why people don't visualise uncertainty" topic which is on the website. 
- Added some other experiment ideas for future sections (although I haven't read that much literature on the topics so I am not sure if they are good ideas or not)
  
#### CassowaryR
- Made the hex sticker and added it to the [repo](https://github.com/numbats/cassowaryr) (finally)
- The build and stuff work locally on my computer, but fail in the github actions. They all have the same error and I don't know what it means.
  
#### Meetings comments and notes
- To test if people are more likely to visualise uncertainty if it is set as a default, make two packages for people to visualise uncertainty. One where the default is uncertainty and one where it isn't and see if people just leave the default or if they don't like the uncertainty so much they change it. Would need to do some finessing so it is not obvious it is Robs package.
- To test if including uncertainty is the best way to show the differentiation between the data and the forecast compare uncertainty to other methods of differentiating the forecast. Other methods such as a gap, a change in the line colour, or a change in background colour.
- People are often presented with risk as odds relative to the average (e.g. your area has 3x more cancer cases than the average). Could be good to test this method of conveying odds relative to a population level (60 people in your area of 10 000 have cancer and the average is 20 per 10 000).
- To test the cognative overload of uncertainty, we can show different designs and see how long it takes to answer a question on it. Alternatively we can fix the time and see which plot gives people the most accuracy. Try to find a motivating example. If we want to compare it to not visualising at all and just displaying threshold values, create a ladder of choices or categories, however in general it is hard to quantify continuous uncertainty.
- Energy data may be a good motivating example for the fan vs paths display of forecasting uncertainty. Di emailled it as an RDS.

## 2022-2023 February 9th
::: {#old-meetings}
:::