---
title: "ETC3250: Introduction to Machine Learning"
listing:
  - id: etc3250-summary
    contents: etc3250-sum/*.pdf
    type: table
    sort: "title desc"
  - id: etc3250-helps
    contents: etc3250-help/*.pdf
    type: table
    sort: "title desc"
---

# Weekly Summaries
These summaries are to help students if you are completely lost in the content and are struggling to grasp the big picture ideas. They are designed to help understand and organise this weeks content. They are not a replacement for lectures or readings and will be quite useless on their own.

::: {#etc3250-summary}
:::

# Tutorial Help Sheet
I have found that students struggle to know where to start with tutorial questions. These files provide simple hints that should help to get started on questions without providing answers. I STRONGLY reccomend doing the tutorial questions without this help sheet if possible to simulate an exam situation. This is a step between doing the question entirely by yourself and just watching me do the question.

::: {#etc3250-help}
:::
