---
title: "BEX6510 Assignment"
---

## Explain how this paper relates to my research

# Summary of Product Plots Paper

## 1 Introduction
- Visualising tables of counts, proportions, and probabilities
- Framework for visualisations of categorical data
- Focuses on  area of charts - area of graphical element is proportional to the underlying count, proportion or probability
- product plots 
  - main idea: width x height = area 
  - and conditional x marginal = joint
  - also have inverse where high dimensional distribution can be factorised into a product of low-dimensional conditional and marginal distributions.
- To illustrate the idea they use the same data from a happiness survey in all examples. 
  - Discrete: age, year
  - Categorical: degree, relative financial status, happiness, health, marital status, sex
  - Continuous: wstall (probability weight)?

## 2 Related Work
- Other efforts to develop domain specific languages for visualisation are:
  - APT [6] and VisQL [7]
    - *Add notes from these papers*
    - . This work is similar but carves out a smaller niche.
    - Compared to these product plots are less expressive but more efficient because the number of primitives (simple elemements) required to describe the smaller domain is smaller (?)
  - HiVE [8]
    - *Add notes from this paper*
  - Polaris [9]
    - *Add notes from this paper*
    - essentially a 3D extension of the trellis framework [10,11]

## 3 Graphical Primitives
- area must be proportional to count.
  - key constraint for area plots
  - total area is usually constrained
- partitions must be disjoint.
  - to be able to see the complete area each rectangle must be not overlapping. 
- partitions must be rectangular
  - allows many interesting pecterptual tasks to only require comparing lengths or positions along a common scale 
  - these are easier than comparing areas
  - little evidence rectangles are the best shape for comparison [15,16]
- These constraints give rise to 4 graphical primitives

### 3.1 1d primitives
- There are three 1d primitives
  - bars: height s proportional to value and width is equally divided. Occupy mean(x-max(x)) of the total area *(???)* isnt that the negative of the whitespace?? shouldnt it be mean(X/max(X))
  - splines: width proportional to value, height occupies full range.
  - tiles: No restrictions on height and width, just tile the plane with rectangles and try to keep the aspect ratio of each rectangle close to 1. A squarified treemap.
- Each visualisation has strengths and weaknesses
  - easy to compare the value associated with bars because comparing position on a common scale
  - splines and tiles are harder to read but work better reccursively

### 3.2 2d primitives
- all 2d primitives are created by combining 1d primitives except for one
  - fluct: has height and width proportional to the square root of the count and is arranged on a rectangular grid formed by the levels of the two variables. 
  - allows comparisons both vertically and horizontally
  - special case occurs when two variables are jointly uniformly distributed, usually as a result of conditioning. useful for identifying missing combinations


## 4 Probabulity and Plot Products
- To construct plots of higher dimensions we need a way to decompose them into 1d and 2d components.

### 4.1 Joint distribution are the product of marginals and conditionals
- turn data into a PMF
- Variables are happy and sex are shown in several tables. 
- Joint distribution
  - Q: what proportion of all people are male and very happy?
- Conditional distributions
  - Q: what proportion of males are not too happy?
- Marginal Distributions
  - Q: What proportion of respondents were male? What proportion were very happy?
- Have the equation $f(x|y) = f(x,y)/f(y)$
  - Therefore given a conditional and a marginal we can find the joint distribution
  - $f(x,y) = f(x|y)f(y)$
  - Only the joint distribution contains the full information about the relationship between all variables involved
  - can get the marginal distribution by integrating/summing the other variable out, i.e. $f(x)=\int_y{f(x,y)}$
  - These definitions extend to higher dimensions
    - $f(x,y,z) = f(x,y|z)f(z)$
    - $f(x,y,z) = f(x|z,y)f(z,y)$
    - $f(x,y,z) = f(x|y,z)f(y|z)f(z)$
- Therefore we can build any high dimensional PMF as a product of low-dimensional conditional and marginal PMFs
- Use low-dimensional primitives as graphical analog of this multiplication

### 4.2 Area is the product of height and width
- area is also a product so it can be connected
  - e.g. 1 mosaic plot: height f(sex|happy) X width = f(happy) = area f(sex, happy)
  - e.g. 2: stacked bar chart: position f(happy) X proportion f(sex|happy) = length f(sex, happy) ~ area = c*f(happy, sex).
- Algorithm gives a rough idea of computation
  - calculate one marginal and i conditional distributions
  - for each probability in the marginal distribution, 
    - divide the probabilities (aka the bounds) into i sets of new bounds, one for each level of the categorical variabe. 
    - if i=1 like in the example we keep the original bounds
    - for each new bound there is a matching conditional distribution, call the partition function
    - drop one element from the list of drawing primitives
- Different partitions reveal different features
  - Hard to identify if this is because they used splines for both of the first plot but splines and bar for the second plot or because of the different distributions.
  - $f(marial,age) = f(marital|age)f(age)$ highlights most young people are unmaried
  - $f(marial,age) = f(age|marital)f(marital)$ highlights few unmarried people over the age of 30
  - I am also not sure how much I agree with this assessment of what the plots say. I don't disagree with the premise though. I do wonder if that is because both comments are about being unmarried.
- Conditioning is also a useful tool because it allows us to remove relationships that are known or uninteresting.
  - Give example of $f(happy, health, financial)$
  - When show all as raw proportions $f(happy, health, financial)$ = $f(happy| health, financial)f(heath,financial)$ your main take away is that most people are in good health and average financial standing, however it is difficult to see how happiness varies within these conditions
  - If you condition on health and financial status, comparing happiness across these groups becomes easier because comparing positions along a common scale is an easier perception task.
  - Depending on the comparison we are most interested in, we can make it easier to compare across different variables

## 5 Existing Plot Types
1D
  - Bar chart (hbar)
  - Column chart (vbar)
  - Spineplot (spine)
  - Fluctuation chart (fluct)
2D
  - Stacked bar chart (1hbar and 1vspine)
  - Nested bar chart (2 hbars)
  - Equal bin size (1 fluct and 1 vspine)
  - Mosaic plot (alternating hspine vspine)
  - Double Decker (n-1 hspines and 1 vspine)
  - Treemap (n spines)
  - Squarified treemap (n tiles)
  - Generalised treemaps (any plot ending with a tile)
  - Trellis graphics (similar but not identical, created by conditioning in tellising variables)

## 6 Display Considerations
- Hard to label axis
  - often two variables end up on the same axis so we cant label it.
  - there are other ways to label the axis other than colour
    - e.g. text labels used to occupy the space of the region they label
    - in the interactive setting can have linked brushing from high dimensional to low dimensional plots
    - some apsect ratios are more aesthetically pleasing, e.g. the square for the fluct. wonder if aspect ratios close to the golden ratio might be more appealing
    - does not seem to be previous work on aspect ratios and aesthetics although they do seem to affect perception
    - need more research on aesthetics and usability

## Variations and Extensions
### 7.1 Weighting
- instead of counts can plot weighted data
- i.e. redo plots where the data is weighted because of sampling or some other reason
- weights are also useful to move from number of countries to number of people
### 7.2 Continuous Data
- instead of counts can plot continuous data
- trivially extended by binning the continuous data to make them discrete
  - can do bins of equal width OR bins containing an equal number of points
- extension allows product plots to also describe histograms and spinograms
  - no gaps are displated between adjacent rectangles when displaying continuous data
- more theoretical approach is to increase number of bins infintesimally leading to a probability density function
  - approach can include one continuous variable but two variables need an additional aesthetic such as colour to visualise a 2d joint density.
  - >=3 continuous variables breaks the product plots framework
  - if you express the innersmost proportion with colour (instead of area) can describe dimensional stacking (apparently a SPLOM is dimensional stacking)
  
### 7.3 Area not proportional to weight
- relax display constraints
- to distinguish between zeros, missing values, and very small values
- zero weight should have zero area but instead set it to be at a minimum perceptable size.
  - set as a different colour to let the reader know the area=weight rule is violated
- could also  be useful to restrict max value so you can see other small values
- could also do other non linear transformations
  - e.g. Tukey applied the technique to histograms where the y axis has a square root scale

### 7.4 Non-disjoint partitions
- relax display constraints
- e.g. cascaded treemaps 
- makes it easier to see all the levels of the hierarchy and highlights the structure
  - e.g. each of $f(sex)$, $f(marital, sex)$, and $f(happy|sex, marital)$ get a layer.
  - hard to tell when something is $f(X|Y)$ or $f(X,Y)$

### 7.5 Non-rectangular partitions
- relax display constraints
- pie chart not retangular and does not fall into the framework, but it does relate
  - it is a hspline draw in polar coodinates with the x-coordinate mapped to angle and the y coordinate mapped to radius
- Other plots that are product plots drawn in polar coodinates
  - Wind rose and fourfold displays (1 hbar and 1 vspine)
    - Nightingales coxcomb is similar but the slices overlap so it violates the disjoint area constraint
  - Concentric pie chart (1 hspine)
  - Doughnut plot (1hspine and 1 vspine)
  - Racetrack plot (1 vbar)
  - Infoslides (n vbars)
- research suggests that visualisations in polar coordinates are harder to read that visualisations in cartesian coordinates
- y-axis must be square root transformed to ensure that counds stay proportional to areas
  - Fan-lenses and Stasko's radial displays deliberatrely do not do this to emphasise the outer levels.
- Other non-rectangular graphics
  - circular treemaps
  - space-filling curves
  - voronoi treemaps

## 8 R Package
- made an R package called productplots
- two main functions
  - prodcalc: computes the coordinates of each rectangle
  - prodplot: displays the rectangles with the ggplot2 package
- each graphical primitive is represented by a function (e.g. hspine()) which allows you to write a new function and use the existing calculation and display algorithms

## 9 Conclusion
- Framework is successful at describing many existing graphics that display tables of counts, proportions and probabilities
- framework leads to many possibilities as a 4d PMF can be factorised in 5 different ways, with 24 different ways of ordering the variables. Have 5 yeas of displaying a 1d PMF and 1 way of displaying a 2D pmf
  -  defines a large space of potential plots. Have $24*(5^4+5^2+5^2+5^2+1)=16824$ plots before we consider conditioning
  - IDK where that number came from
    - on the function end:
      - 24 combinations of variables
      - 5 ways of factorising
      - 24*5 different factorisations
      - 5 ways of displaying a 1D PMF
        - within the factorisations there are (4, 2, 2, 2, 0) 1D PMFs
      - 1 way of displaying a 2D pmf
        - within the factorisations there are (0, 1, 1, 1, 2)
        - it looks like it is done
          $5*5*5*5$
          $5*5*1$
          $5*1*5$
          $1*5*5$
          $1*1$
- Well thought out interactions make it easier to navigate this space & developed a prototype as part of the cranvas suite of interactive grahics
- also exploring the connection between product plots and log-linear (AKA poisson) models (the statistical models most commonly used for count data)
  - e.g. looking for straight lines in a mosaic plot corresponds to a formal test of independence between variables
  - generally we are interested in connections between visualisation and formal statistical tests
  - also how significant coefficients can help us choose a set of useful plots
  - given a question can we select appropriate plots? given a plot can we suggest questions it might answer?
- Product plots need to be extension to display uncertainty
- Continuous data is incorperated in a simplistic manner.
  - can it be extended for something like the average shifted histogram or the kernel density estimate
  
# Extension of Work
- Does this work extend to expected values or visualisations of other mathematical process?
- Could be expanded by looking at which other perceptual tasks are combinations of others
- extension to continuous case
- extension on the connection between what questions are best suited for each distribution
- Can the questions be combined similarly the way we can combine the PMF and the graphics
- Connections between formal statistical tests and visualisations
- uncertainty visualisation extensions