---
title: "What do we mean when we talk about uncertainty?"
author: "Harriet Mason"
date: "2023-03-11T00:00:00Z"
lastMod: "2023-03-11T00:00:00Z"
categories:
  - data visualisation
  - statistics
tags:
  - data visualisation
  - statistics
editor: 
  markdown: 
    wrap: 72
---

## High Variance Lifestyles
Recently I asked my doctor if I could be put on some kind of mood stabilisers. I had been experiencing a lot of aggrevation, stress and general negative vibes as a result of trying to tie up the tenancy of my due to having to engage with my ex-housemate. Over the few weeks prior to my doctor appointment, my housemate sara had hit my dog, hit me in the face with a plate (which resulted in the police being called to the house), stole some of our stuff, refused to sign the lease transfer documents, left a large amount of broken furniture at the house, refused to pay her outstanding $700 in rent and bills, set fire to the mantle and refused to fix it, constantly posted on social media calling myself and my other housemates crazy children, tried to convince the person who we found to take over her lease to not move in, and finally ghosted us when we tried to confront her about these things. At one point the house group chat turned to asking if it would be easier to just kill her and deal with the police than continue to deal with her. Upon hearing this my doctor said he didn't think I needed mood stabilizers because someone terrorizing your place of living and stealing your things and assulting you would lead any reasoable person to be upset and he didn't think mood stabilisers would help. While I somewhat agree, seeing her message the new housemate saying she "wants this to be over and done with already" should not be enough to send me into a two day rage. This conflict which would seem completely out of the ordinary to most people is a regular occurence for me and while I understand it is extreme, at some point I have to be able to work at a job. If my plan for emotional regulation is to assume my mood will usually be in the healthy range and handle the few cases it isn't when they arise, then I might as well accept my current situation which is 100 productive days in the year. There are obvious triggers and ways to manage this. I will never be able to entirely remove "off days" from my life, but I can decrease their frequency and length with a better understanding of its sources. If I understand *what* about my demon housemate Sara and others like her sends me into an angry death spiral, I can redirect the energy and have a better control of the situation. Specifically, understanding the sources of the variance in my life will help me understand the best ways to manage it. Uncertainty in a model is quite similar. In a lot of ways, I think of my struggles to contain my mood as similar to my struggles to estimate uncertainty.

## Sources of Uncertainty
Lets start this section off with a simple plot hopefully everyone has seen before. This is a plot taken from Forecasting: Principles and Practice. It is a simple depiction time series data, but I have also included a forecast (using an ARIMA model but that is unimportant) that has some uncertainty surrounding it.

```{r}
library(fpp3)

h02 <- PBS |>
  filter(ATC2 == "H02") |>
  summarise(Cost = sum(Cost)/1e6)
h02 |>
  mutate(log(Cost)) |>
  pivot_longer(-Month) |>
  ggplot(aes(x = Month, y = value)) +
  geom_line() +
  facet_grid(name ~ ., scales = "free_y") +
  labs(y="", title="Corticosteroid drug scripts (H02)")

fit <- h02 |>
  model(ARIMA(log(Cost) ~ 0 + pdq(3,0,1) + PDQ(0,1,2)))
fit |> gg_tsresiduals(lag_max=36)

augment(fit) |>
  features(.innov, ljung_box, lag = 36, dof = 6)

h02 |>
  model(ARIMA(log(Cost) ~ 0 + pdq(3,0,1) + PDQ(0,1,2))) |>
  forecast() |>
  autoplot(h02) +
  labs(y=" $AU (millions)",
       title="Corticosteroid drug scripts (H02) sales")
```

Now there is a LOT happening under the hood here. Not calculation wise (well actually there is but that's not what I'm referring to) but rather in terms of the assumptions we are making about our uncertainty.


In order to communicate uncertainty, you first need to be able to calculate it. When we have an estimate and we need to construct a confidence interval around it, however this is not as straight a shot as we might think. When I try to think about estimating a true confidence interval, accounting for every possible random event, I become so overwhelmed it gives me anxiety. When I make a confidence interval, what information do I account for? What do I do about the randomness I know about but can't quantify? What about the randomness that is out there, waiting for me, that I can't even consider, or imagine? 

Lets make this easier. If I use the fable package to  have some time series data, and I make some forecast, 
* Incorrect model or distribution
* Measurement errors
* Sampling error
* Events outside the sample
* Black Swan Events (pandemic)

# Random notes
- interesting that we give confidence intervals as 95%. Every way we talk about uncertainty is directly related to hypothesis testing which is a very non-intuitive way of thinking about uncertainty. What if we did epistemic and aleatory confidence intervals. This may be a stupid idea when I read it later, not at midnight.
- From the Role of Uncertainty "We can see that trust it is highest when the user is either aware of no uncertainties or mistakenly believes there are no uncertainties". This makes me suspect that people are trusted more when they don't display uncertainty BECAUSE the audience has assumed there is none.  If you don't display uncertainy, I think it is assumed there is none. maybe we could test this by making people aware of uncertainty and not and seeing if their reaction to to the plot when there is no uncertainty displayed mimics their beliefs when they know for certainty there is no uncertainty. Like get them to do a decision making task or something. It makes me think about the cognative test I had to do where uncertainty existed but was not made explicitly clear to me.
- Could be fun to test what testing method provides a better understanding of audience insight? Is that too meta?
- "Open questions generally support visualisation overviews rather than details views" I wonder if the way we ask questions about visualisations changes the way people see them.