---
title: "Research Ideas"
listing:
  - id: parts
    contents: parts
    type: default
    fields: [image, title, description]
  - id: ideas
    contents: ideadumpster
  - id: confirmation_report
    contents: confirmation_report
  - id: confirmation_presentation
    contents: confirmation_presentation
---
# Overview of Topic
## The current perspective on visualising uncertainty
Current research in visualising uncertainty seems to have a focus on designing new options for visualising uncertainty for specific types of data. Typical papers comparing visualisation methods seem to fit into one or both of the follow categories:

1) a paper that suggests a new visualisation method for a specific type of data  

2) a paper that compares two existing methods to idenfiy which is better.  

Generally the goal seems to be to increase the number of options we have in our "visualisation bag" or to better understand when we should use each type of plot. This research focuses on designing plots for different types of data, not on what we want to find in our data. For example, if you have two continuous variables you will typically make a scatter plot. This plot can tell you almost everything you would want to know about the variable, you can tell if there is correlation or non-linearity between these two variables, you can identify the distribution of each variable, you can even identify outliers or leverage points. While the scatter plot is an extreme example (you can't tell this much from every plot obviously), the general rule of making a plot according to the type of data you have and then letting the plot tell you the important information is typically how plotting works. Since a plot is seen as an exploratory method and not a statistical test, making plots based on the data and not what we want to find out is intuitive. Therefore, since uncertainty is secondary to our data (we have temporal uncertainty and spatial uncertainty and whatnot) we should visualise uncertainty the same way. Therefore each data type (for example) should have an uncertainty method associated with it, reguardless of the source of uncertainty.

## Why I don't like this perspective
Unfortunately the literature itself seems to be split down the middle on whether uncertainty is a secondary feature of our data, or its own object deserving of its own visualisation methods. It is wildly confusing to read papers on the topic because this clear difference in ideology is neither acknowledge or discussed. If uncertainty is merely a secondary aspect of the plot, the way we visualise uncertainty depends on the data we have. Temporal uncertainty, spatial uncertainty, normal (?) uncertainty should all have different methods specific to that type of data. If uncertainty is its own thing, we should consider the best way to visualse the specific distribution we are concerned with (and incorperate it into a visualisation of the data if the context is relevant). This distinction may seem pointless at a surface level, but when you actually consider how we estimate uncertainty and why we visualise it the distinction becomes important.

Lets first consider the scenario where uncertainty is specific to the type of data, basically the way we currently think about visualising uncertainty. In this context, what is temporal uncertainty? Something as abstract as "uncertainty related to time data" cannot be quantified or drawn. If I give you a data set and ask you to plot the "temporal uncertainty: with no other information you will be lost. So what is temporal uncertainty? Is it measurable? Is it something you can plot? You may try and describe to me what temporal uncertainty is, but you will likely end up describing uncertainty related to a forecast, or variance of a variable, or even model residuals. These are not "temporal uncertainty", they are the distribution of a prediction, a variable, or of a model. None of these things are specific to temporal data. This may just sound like me being pedantic about poor naming, but this incorrect framing of uncertainty leads to very inconsistent research.

Because we view uncertainty as a secondary feature of the data, and not as something we have constructed, we don't think about uncertainty visualisations with the "goal of the uncertainty" in mind. The problem is, we had a goal in mind when we estimated the uncertainty. The uncertainty related to whether or not two variables are significantly different from each other is different to the uncertainty related to whether or not each variable is significantly different from 0. Unlike making plots of data, where we can make a single plot and use it to get information on multiple hypothesis, in order to plot uncertainty we need to already have a hypothesis in mind and a plot made for one question cannot be used to answer another question. So not only is uncertainty not specific to the data, its not even specific to the random variable. Uncertainty is specific to some hypothesis (in an abstract sense, you don't literally need a hypothesis). If you make a forecast and want to know the confidence intervals associated with each point prediction, that would have a different confidence interval to the path of a 5 step ahead forecast. So not only does it not make sense to think about "temporal uncertainty" the concept of even visualising the uncertainty of some random variable without knowing what you want to know, is futile. If you ignore this clear distinction, you are going to misuse uncertainty techniques and beleive they are interchangable for every hypothesis, and thus draw incorrect conclusions. If you have ever used an error bar for a hypothesis that is not idenfiying a statistically significant range of values (using it to identify if two variables are statistically different from each other is also incorrect) then you are guilty of the exact issue I am talking about. 

While you may be sitting here, thinking "this is obvious and pointless to point out" I suspect you are not as aware of how much you interchangably use different uncertainty methods. As a matter of fact, I can't think of a single unit in my undergraduate degree that didn't make this mistake at least once. Therefore it is unsurprising that every paper on uncertainty visualisation research seems to ignore this issue entirely. Not only do they ignore this, but many are written with the perspective of trying to find a "best" or "universal" uncertainty method. Ignoring the hypothesis that generated the uncertainty then leads to the uncertainty questions asked in every paper being different. At no point is it considered if an uncertainty visualisation should depict statistical significance or significant difference between variables. If the plot should tell us which outcome is more probable or if I should be able to make accurate predictions. Maybe it should just give an idea of the distribution of each variable. This leads to the obvious question, which of these questions should the "best" uncertainty visualisation allow me to answer? There is an unspoken assumption prevailing in uncertainty visualisation that the uncertainty distribution associated with one hypothesis can just be swapped out for another. An assumption that the literature itself seems to disprove since there are many papers that are "contradictory" if you view them through the lense of finding a best plot, but strangely consistent when you reframe the conclusions through the lense of the "best plot for this hypothesis". Unfortunately this evidence is almost always used to highlight a failing in the plot, rather than a failing in the question.

My solution to this problem is to design uncertainty visualisation rules that are irrelevant to the data, but instead focus on the question being asked. I would review the research in uncertainty visualisation and reframe the conclusions with the goal of finding the best uncertainty method for each question (rather than for the type of data). Similar to how we have simple rules for effective data visualisation (continuous + continuous = scatter plot, discrete + continuous = box plot, etc) I would like to define rules for uncertainty visualisation (variable significance = error bar, probability comparison = HOPS plot, etc). Using this framework, the concept of designing a method for visualising temporal uncertainty becomes pointless.

Additionally (for possible future work) this process would change the way we view problems such as visualising spatial uncertainty. The question of how to constuct uncertainty plots for complicated data types (such as spatial data) is no longer driven by desiging an abstract uncertainty visualisation method for spatial data. The goal would be to find the best way to combine the most appropriate uncertainty visualisation for the relevant question and the best plot for the type of data. These methods may be able to be combined onto a single plot, however there may be cases where two different plots (one for the data and one for the uncertainty) is more appropriate and effective. Under this

This is a long winded overview of the general motivation for the change in perspective in visualising uncertainty. The five posts below go into more detail providing citations and evidence for the suggestions I make in the overview above. Directly below is a short summary of what each of the five parts cover. 

This section discusses why, despite many viable techniques for visualizing uncertainty and a moral consensus that it is the correct thing to do, most authors still ignore uncertainty in their visualizations. A large problem seems to be a a general inability to quantify and articulate what exactly uncertainty is and a view that it is of secondary imporance to estimates.


## The Idea in 5 Parts
::: {#parts}
:::

### Part 4: Rules for Communicating Uncertainty
In this section I go back to papers written on defining uncertainty and reinterpret their conclusions. Rather than ask "Which method of uncertainty visualisation is better (for this data)" I ask "Which method of uncertainty is better for this question". This will give us a set of rules backed by scientific evidence that we can use to decide which uncertainty method is the best at conveying the answer to a specific question. 

### Part 5: Applying this Problem to Energy Data
Finally, I will go through a data visualisation problem from begining to end to show how this method might be used with a typical question about uncertainty. Starting with defining the uncertainty and stating the assumptions/limitations. Then using the rules of visualising uncertainty to present different visualisations that answer different uncertainty questions about the data.

# Confirmation 
## Report
I have put my confirmation report here for the time being because I am not sure where to put it.

::: {#confirmation_report}
:::

### Todo List
#### Monday
- [x] Finish writing Hierarchy section
- [x] Finish sorting all the miscelaneous notes at the end of the report
- [x] Organise todo list of remaining tasks
- [x] Remove second error bar plot
- [x] Redo features drawing with actual names
- [x] Add two plot to the motivation
- [x] Fix formatting of plots (in R stuff)
- [x] Work out what is stopping PDF from knitting
- [x] Format timeline into table
- [x] Read over Motivation - Thesis Overview:
  - Spell check
  - Readability check
  - Add econometrics question to begining
  - Make uncertainty definition and use more cohesive
  - Cite AEMO conversation 
  - Make it clear scholarship is from AEMO and we are already talking to them (in project 2 and 3)
  - Expand on chapter 3
  - Rewrite landscape section to make it more cohesive with report

#### Tuesday
- [x] Spend forever fixing the vizumap error :(
- [x] Add hypothesis test visualisation
- [X] Add supervisor list to title section
- [x] Find lost lineup plot paragraph and add back in
- [x] Read over Chapter 1 - End:
  - Rewrite landscape section to match paper
  - Mathematical expressions for distributions
  - Make it clear distribuitons can come from an unspecified null
  - Make it clear that this is a way to assess the information presented in a distribution and connect the ideas in to statistics.
  - Make sure it is conveyed why this abstraction is better
  - Redo spell check
- [x] Cite paper AEMO team sent
- [x] Fix formatting of plots (except full page problem)
- [x] Add HOPs plot to example

#### Wednesday
- [x] Supervisor Comments:
  - [x] Check for lower case r for R
  - [x] Move cassowaryr to sections at the end of the report called "additional activity"
  - [x] Add 3 month break to timeline
  - [x] Cut fable package section on page 5
  - [x] Cut chapter 3 discussing of random pacakge
  - [x] Fix captions to follow structure
  - [x] Move why section to begining
  - [x] Reference anscombes quartet in last section because it is contradictory to that motivating questions
  - [x] Add in "how to read section" that explains the stage of the work being presented and how the report is structured
  - [x] Chapter 1 give another explanation of coming structure
- [x] Final read over + spell check

### Additional REPORT ideas
- I couldn't find a citation for “show me the data”. Check again later?
- gestalt principles?
- Check HOPS plot paper and run through how a hops plot is made to make sure I have it right
- Change spatial example to Australian data from American
- add parallel co-ordinate plot, line plot, slope graph, parallel sets plot visualisation
- Check circle error bar is accurate
- Add type 1 and other probabilities into error plot

## Presentation

::: {#confirmation_presentation}
:::

### Todo List
#### Saturday
- [x] Set up quarto slides

#### Sunday
- [x] Figure out quiz theme
- [x] Write intro to presentation
- [x] Map out all quiz questions
- [x] Question 1: Anscombe's Quartet

#### Monday
- [ ] Question 2: Decisions Under Certainty
- [ ] Question 3: Decisions Under Uncertainty
- [ ] Formatting of slides
- [ ] Draw apples and oranges icon


#### Tuesday
- [ ] Finish Question 3
- [ ] Question 4: Visualising a Distribution
- [ ] Serious Section 
- [ ] Add icon to slides
- [ ] Question 5: 
- [ ] Question 6: 
- [ ] Question 7: 
- [ ] Question 8:
- [ ] Full Read through with edits
- [ ] Set up quiz for Sophie to give out
- [ ] Rehearse Speech
- [ ] Present for Housemates

#### Wednesday

### Additional PRESENTATION ideas
- Add countdown timer for each quiz question
- Print QR code so people can hand it around and join the quiz
- Add quiz music for each quiz question
- Quiz show boarder to quiz intro slide
- Add sign-posting into slides
- Make references into footnotes
 
# Idea Dumpster
This is just the file that holds the ideas I had that may or may not be terrible. Not for anyone to read ever.

::: {#ideas}
:::