---
title: "Uncertainty Grammar of Graphics"
---
This results in a series of experiments where the visual aspects of the graphic are not even required to anticipate the experimental results. Ideally this problem would be avoided by defining the information in a graphic using *The Grammar of Graphics* since it is a sufficient summary of the information in a graphic and it allows a plot to be considered a statistic [@Vanderplas2020]. The process for summarising the information in a plot using *The Grammar of Graphics* is depicted in @fig-pipeline [@Leland2005]. Unfortunately, *The Grammar of Graphics* is not perfectly suited to summarise the information in an uncertainty visualisation since it assumes that we start from a finite data set. Very often uncertainty is expressed using a distribution or a resampling method that does not have an upper limit on the "sample size". Additionally many uncertainty visualisation experiments notice an interaction between sample size and graphic effectiveness [@Kale2018; @Newburger2022; @Hofmann2012], an effect that is likely caused by a difference in human perception of mass versus sample. Additionally, *The Grammar of Graphics* behaves strangely when the sample size is adjusted and it the distance between two graphics becomes less consistent. @fig-infintegraph shows how three graphics defined by *The Grammar of Graphics* can change as n approaches infinity. The two graphics that are very similar according to the *The Grammar of Graphics* diverge into different graphics, and two graphics that are very different, converge into the same graphic. This means the statistics visualised in the plot as well as the *The Grammar of Graphics* may not be an adequate to summarise the information in a plot that is being used for uncertainty visualisation. Some authors have noticed difficulties with visualising distributions using `ggplot2` and created extensions that make showing distributions more intuitive [@Pu2020; @Kay2023], however these extensions do not address the core discrepancies with uncertainty visualisation and *The Grammar of Graphics*. This does not mean *The Grammar of Graphics* should be abandoned when we attempt to summaise the information in an uncertainty visualisation, very often visations use the same sample to generate all their plots, so this issue is not always present, however these limitations should be kept in mind when analysing uncertainty visualisations using *The Grammar of Graphics*.

![(The grammar of graphics data analysis pipeline from @Leland2005 written in black, with the tidy data equivalent written in blue. The product plot framework and the grammar of probabilistic graphics frameworks are in green. It can be seen that the grammar of graphics provides a set of instructions that create a graphic, however the inferential power of this graphic is not considered and relies on many additional assumptions that are not defined by the grammar.](grammarofgraphicspipeline.jpeg){#fig-pipeline}
 
 ![This graphic shows three simple graphics made from the same data set that diverge according to the grammar of graphics. Despite being distinct graphics from a stage as low down as the statistic (or data manipulation in the tidy data framework), as our sample size increases to infinity, the grahics converge to the same distribution and become visually indistinguishable. ](infinitegraph.jpeg){#fig-infinitegraph}